food_factAPI
Zarebin/internship-projects-python pull request #32
Opened 2022-06-09 12:53 UTC by sasukepashapoor

2022-06-09 20:28 UTC, hr-samsami requested changes
1. add your app name to INSTALLED_APPS in crowd_server/settings/base.py
2. add the path of your API to urlpatterns in crowd_server/urls.py

2022-06-09 20:28 UTC, hr-samsami commented on crowd-server/crowd_server/apps/food_fact_API/apps.py
> +
Code missing: add config class like the bellow
<code>
 class ImageLabelConfig(AppConfig):  
 default_auto_field ='django.db.models.BigAutoField'
 name =crowd_server.apps.image_label'
</code>

2022-06-14 07:36 UTC, hr-samsami approved these changes

2022-06-14 10:23 UTC, ketabi requested changes

2022-06-14 10:23 UTC, ketabi commented on crowd-server/crowd_server/settings/base.py
> +    'crowd_server.apps.food_fact_API'
It's better to be `'crowd_server.apps.food_fact'`

2022-06-14 10:23 UTC, ketabi commented on crowd-server/crowd_server/urls.py
> +    path('food_compare/', include('crowd_server.apps.Food_Fact_API.urls')),
`     path('food_fact/', include('crowd_server.apps.food_fact.urls')),1

2022-06-14 10:23 UTC, ketabi commented on crowd-server/crowd_server/apps/food_fact_API/apps.py
> +    name = 'crowd_server.apps.Food_Fact_API'
change the name

2022-06-18 15:55 UTC, ketabi approved these changes
Great

2022-06-18 17:01 UTC, merged